; ***********************************************************************************************
; * UNIVERSIDADE FEDERAL DO RIO GRANDE DO NORTE						        *
; * CENTRO DE TECNOLOGIA								        *				
; * DEPARTAMENTO DE ENGENHARIA ELÉTRICA                                                         *                 
; * TRABALHO DE CONCLUSÃO DE CURSO						               	*
; * PROFESSOR ORIENTADOR: JOSE ALBERTO NICOLAU					                *
; * ALUNO: BERNARDO XAVIER DA SILVA 					                        *	
; * "BOTÃO DE PÂNICO"   							               	*
; ***********************************************************************************************
                                                                      
; * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
; * DATA : 31/08/2010 
; * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
;
; * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
; *                             DESCRIÇÃO GERAL                             *
; * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
; ESTE CÓDIGO TEM POR OBJETIVO RECONHECER UMA SITUAÇÃO DE PERIGO A PARTIR DO 
; RECEBIMENTO DE UM SINAL VINDO DE UM BOTÃO ("BOTÃO DE PÂNICO") E PREPARAR
; UM MODEM GSM PARA MODO DE ENVIO DE SMS A FIM DE ALERTAR OS INTERESSADOS ACERCA
; DO ACONTECIDO.  
; * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
; *                         CONFIGURAÇÕES PARA GRAVAÇÃO                     *
; * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *

 __CONFIG _CP_OFF & _CPD_OFF & _DEBUG_OFF & _LVP_OFF & _WRT_OFF & _BODEN_OFF & _PWRTE_OFF & _WDT_OFF & _XT_OSC

; * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
; *                            DEFINIÇÃO DAS VARIÁVEIS                      *
; * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
;  ESTE BLOCO DE VARIÁVEIS ESTÁ LOCALIZADO LOGO NO INÍCIO DO BANCO 0

	CBLOCK	0X20			; POSIÇÃO INICIAL DA RAM

		BIT
		TEMPO0
		TEMPO1
		TEMPO2
		COUNTER
		AUXCOUNTER
		AUX				; REGISTRADOR AUXILIAR DE USO GERAL.
		AUX1			; NÚMERO DO BYTE RECEBIDO.
		AUX_DEMANDA		; COMPARAÇÃO DE FIM DE INTERVALO DE DEMANDA.
		AUX_DADO_REP	; VERIFICA SE O MESMO DADO FOI ENVIADO 3 VEZES CONSECUTIVAS (FIM DE INTERVALO DE DEMANDA)
		UNIDADE			; ARMAZENA VALOR DA UNIDADE
		DEZENA			; ARMAZENA VALOR DA DEZENA
		CENTENA			; ARMAZENA VALOR DA CENTENA
		ATIVA1			; BYTES DO NUMEROS DE PULSOS
		ATIVA2			; DE ENERGIA ATIVA
		REATIVA1		; BYTES DO NUMEROS DE PULSOS
		REATIVA2 		; DE ENERGIA REATIVA
		SEGUNDOS		; BYTE MENOS SIGN. DO NÚMERO DE SEGUNDOS RESTANTE.	
		FLAGS			; CONJUNTO DE TODOS OS FLAGS USADOS NO PROGRAMA

		CRC_L				; REGISTRADORES UTILIZADOS PARA
		CRC_BUFF		; A ROTINA DE GERAÇÃO DO CRC.
		COMP_CRC

		POLY			; POLINÔMIO USADO NA GERAÇÃO DO CRC.
		PROB
		CONT

	ENDC

; * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
; *                DEFINIÇÃO DAS VARIÁVEIS INTERNAS DO PIC                  *
; * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
;  O ARQUIVO DE DEFINIÇÕES DO PIC UTILIZADO DEVE SER REFERENCIADO PARA QUE
;  OS NOMES DEFINIDOS PELA MICROCHIP POSSAM SER UTILIZADOS, SEM A NECESSIDADE
;  DE REDIGITAÇÃO.

	#INCLUDE <P16F877A.INC>		; MICROCONTROLADOR UTILIZADO


; * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
; *                      DEFINIÇÃO DOS BANCOS DE RAM                        *
; * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
;  OS PSEUDOS-COMANDOS "BANK0" E "BANK1", AQUI DEFINIDOS, AJUDAM A COMUTAR
;  ENTRE OS BANCOS DE MEMÓRIA.

#DEFINE	BANK1	BSF	STATUS,RP0 	; SELECIONA BANK1 DA MEMORIA RAM
#DEFINE	BANK0	BCF	STATUS,RP0	; SELECIONA BANK0 DA MEMORIA RAM

; * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
; *                           CONSTANTES INTERNAS                           *
; * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
;  A DEFINIÇÃO DE CONSTANTES FACILITA A PROGRAMAÇÃO E A MANUTENÇÃO.
;  VALORES PARA ESCRITA NO DISPLAY

      	      				 ;.GFEDCBA
ZERO		EQU B'00111111'		; VALOR 0 NO DISPLAY
UM		    EQU	B'00000110' 	; VALOR 1 NO DISPLAY
DOIS		EQU	B'01011011' 	; VALOR 2 NO DISPLAY
TRES		EQU	B'01001111' 	; VALOR 3 NO DISPLAY
QUATRO		EQU	B'01100110'		; VALOR 4 NO DISPLAY
CINCO		EQU	B'01101101'		; VALOR 5 NO DISPLAY
SEIS		EQU	B'01111101'		; VALOR 6 NO DISPLAY
SETE		EQU	B'00000111' 	; VALOR 7 NO DISPLAY
OITO		EQU	B'01111111' 	; VALOR 8 NO DISPLAY
NOVE		EQU	B'01101111' 	; VALOR 9 NO DISPLAY

; * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
; *                    DECLARAÇÃO DOS FLAGs DE SOFTWARE                    *
; * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
;  A DEFINIÇÃO DE FLAGs AJUDA NA PROGRAMAÇÃO E ECONOMIZA MEMÓRIA RAM.

#DEFINE		ATIVA_F		FLAGS,0
#DEFINE		REATIVA_F	FLAGS,1
#DEFINE		REPETICAO	FLAGS,2
#DEFINE		FLAG_DELAY	FLAGS,3	

; * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
; *                                ENTRADAS                                 *
; * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
;  AS ENTRADAS DEVEM SER ASSOCIADAS A NOMES PARA FACILITAR A PROGRAMAÇÃO E
;  FUTURAS ALTERAÇÕES DO HARDWARE.

#DEFINE		RXUSART	PORTC,7			; ENTRADA DE RX DA USART

; * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
; *                                 SAÍDAS                                  *
; * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
;  AS SAÍDAS DEVEM SER ASSOCIADAS A NOMES PARA FACILITAR A PROGRAMAÇÃO E
;  FUTURAS ALTERAÇÕES DO HARDWARE.

#DEFINE	LED			PORTD,3			; BARRAMENTO DE DADOS DO DISPLAY
#DEFINE	DISPLAY		PORTB			; ENVIO DE DADOS PRA O DISPLAY DE LCD
#DEFINE	RS			PORTE,0		; INDICA P/ O DISPLAY UM DADO OU COMANDO
					; 1 -> DADO
					; 0 -> COMANDO

#DEFINE	ENABLE		PORTE,1		; SINAL DE ENABLE P/ DISPLAY
					; ATIVO NA BORDA DE DESCIDA

; * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
; *                   VETOR DE RESET DO MICROCONTROLADOR                    *
; * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
;  POSIÇÃO INICIAL PARA EXECUÇÃO DO PROGRAMA

	ORG	0X0000			; ENDEREÇO DO VETOR DE RESET
	GOTO	INICIO			; PULA PARA CONFIG DEVIDO A REGIÃO
					; DESTINADA AS ROTINAS SEGUINTES


;_____________________________DELAY MS_______________________________________
; ROTINA PARA GERAÇÃO DE DELAYS. PODE-SE GERAR DELAYS DE 1ms A 255ms. BASTA
; SE PASSAR O ARGUMENTO PELO WORK E CHAMAR A ROTINA

DELAY_MS				
	MOVWF	TEMPO1		; CARREGA TEMPO1 (UNIDADES DE MS)
	MOVLW	.250
	MOVWF	TEMPO0		; CARREGA TEMPO0 (P/ CONTAR 1MS)

	CLRWDT				; LIMPA WDT (PERDE TEMPO)
	DECFSZ	TEMPO0,F	; FIM DE TEMPO0 ?
	GOTO	$-2			; NÃO - VOLTA 2 INSTRUÇÕES
						; SIM - PASSOU-SE 1MS
	DECFSZ	TEMPO1,F	; FIM DE TEMPO1 ?
	GOTO	$-6			; NÃO - VOLTA 6 INSTRUÇÕES
						; SIM
	RETURN				; RETORNA


; * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
; *                CONFIGURAÇÕES INICIAIS DE HARDWARE E SOFTWARE            *
; * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
;  NESTA ROTINA SÃO INICIALIZADAS AS PORTAS DE I/O DO MICROCONTROLADOR E AS
;  CONFIGURAÇÕES DOS REGISTRADORES ESPECIAIS (SFR). A ROTINA INICIALIZA A
;  MÁQUINA E AGUARDA O ESTOURO DO WDT.

INICIO
	CLRF	PORTB			; LIMPA O PORTB
	CLRF	PORTC			; LIMPA O PORTC
	CLRF	PORTD
	CLRF	PORTE

	BANK1				; ALTERA PARA O BANCO 1 DA RAM
	MOVLW	B'00000001'
	MOVWF	TRISA			; CONFIGURA I/O DO PORTA

	;MOVLW	B'00001111'
	MOVLW	B'00000000'
	MOVWF	TRISB			; CONFIGURA I/O DO PORTB

	MOVLW	B'10011000'
	MOVWF	TRISC			; CONFIGURA I/O DO PORTC

	MOVLW	B'00000000'
	MOVWF	TRISD			; CONFIGURA I/O DO PORTD

	MOVLW	B'00000000'
	MOVWF	TRISE			; CONFIGURA I/O DO PORTE

	MOVLW	B'00000111'
	MOVWF	CMCON			; DESLIGA COMPARADORES ANALÓGICOS
	
	MOVLW	B'00000111'
	MOVWF	ADCON1			; DESLIGA CONVERSORES A/D
	MOVLW	B'10000100'
	MOVWF	OPTION_REG		; PRESCALER 1:32 NO TMR0
					; PULL-UPS DESABILITADOS
					; AS DEMAIS CONFG. SÃO IRRELEVANTES
	MOVLW	B'00100000'
	MOVWF	INTCON			; HABILITA INTERRUPÇÃO DE TMR0
							; DESABILITA TODAS AS INTERRUPÇÕES (GIE=0)

	MOVLW	B'00100110'		; CONFIGURA USART
	MOVWF	TXSTA			; HABILITA TX
							; MODO ASSINCRONO
							; TRANSMISSAO DE 8 BITS
							; HIGH SPEED BAUD RATE


	MOVLW	B'00100000'		; HABILITA INTERRUPÇÃO DE RECEPÇÃO SERIAL (USART)
	MOVWF	PIE1	
	MOVLW	.26				; BAUD RATE = 9600 BAUDS (9615,38 BAUDS)
	MOVWF	SPBRG			; BAUD RATE = Fosc/[16*(SPBRG+1)] <- MODO ASSÍNCRONO, HIGH SPEED

	BANK0				; RETORNA PARA O BANCO 0

; * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
; *                         INICIALIZAÇÃO DA RAM                            *
; * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
;  ESTA ROTINA IRÁ LIMPAR TODA A RAM DO BANCO 0, INDO DE 0X20 A 0X7F

ENDERECAMENTO
	MOVLW	0X20
	MOVWF	FSR				; APONTA O ENDEREÇAMENTO INDIRETO PARA
							; A PRIMEIRA POSIÇÃO DA RAM
LIMPA_RAM
	CLRF	INDF			; LIMPA A POSIÇÃO
	INCF	FSR,F			; INCREMENTA O PONTEIRO P/ A PRÓX. POS.
	MOVF	FSR,W
	XORLW	0X80			; COMPARA O PONTEIRO COM A ÚLT. POS. +1
	BTFSS	STATUS,Z		; JÁ LIMPOU TODAS AS POSIÇÕES?
	GOTO	LIMPA_RAM		; NÃO - LIMPA A PRÓXIMA POSIÇÃO
							; SIM

; * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
; *      PARA INICIALIZAÇAO DO MODEM, NECESSITA-SE DE CERCA DE 15 SEGUNDOS  *
; * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
	
	BSF		PORTD,0		; LED PARA INDICAÇÃO DE DELAY DE 15 SEGUNDOS
	BSF		PORTD,1
	MOVLW	.1
	MOVWF	COUNTER	
	
	
PRECONTAGEM				; PRECONTAGEM É UMA LÓGICA CRIADA PARA GERAR ATRASOS
	MOVLW	.250		; NESSE CASO CARREGANDO O WORK C/ 250 GERAMOS UM ATRASO DE 250ms	
	CALL	DELAY_MS	; 4*250 ms = 1 s	
	INCF	COUNTER		; 60*250ms = 15 s DE ATRASO
	MOVFW	COUNTER
	MOVWF	AUXCOUNTER	; A CADA VOLTA DA ROTINA DELAY_MS INCREMENTA-SE O COUNTER
	MOVLW	.60			; ASSIM QUE O MESMO CHEGAR A 60, COMPARA-SE COM O VALOR 60
	
	XORWF	AUXCOUNTER	; ATRAVÉS DE UM 'XOR', SE IGUAL PASSA PARA O PRÓXIMO PASSO 
	BTFSS	STATUS,Z	; SE NAO, VOLTA-SE AO 'PRECONTAGEM'
	GOTO	PRECONTAGEM

	BCF		PORTD,1		; DESLIGANDO O LED (PASSARAM-SE 15 SEGUNDOS)
	
; * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
; *      COMANDOS NECESSÁRIOS PARA PRÉ-CONFIGURAÇÃO DE ENVIO DE SMS A 9600 BAUDS        *
; * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
	MOVLW	'A'			; A
	CALL 	ENVIAR
	MOVLW	'T'			; T
	CALL 	ENVIAR
	MOVLW	0X0D		; ENTER
	CALL	ENVIAR

	MOVLW	.250		; DELAY PARA ESTABILIZAÇÃO
	CALL	DELAY_MS
	MOVLW	.20		; DELAY PARA ESTABILIZAÇÃO
	CALL	DELAY_MS

	MOVLW	'A'			; A
	CALL 	ENVIAR
	MOVLW	'T'			; T
	CALL 	ENVIAR
	MOVLW	0X0D		; ENTER
	CALL 	ENVIAR		; ENVIADO O CODIGO AT<CR> DUAS VEZES PARA ESTABILIZAÇÃO

	MOVLW	.250		; DELAY PARA ESTABILIZAÇÃO
	CALL	DELAY_MS
	MOVLW	.20		; DELAY PARA ESTABILIZAÇÃO
	CALL	DELAY_MS

	MOVLW	'A'			; A
	CALL 	ENVIAR
	MOVLW	'T'			; T
	CALL 	ENVIAR
	MOVLW 	'+'			; +
	CALL	ENVIAR
	MOVLW	'C'			; C
	CALL    ENVIAR
	MOVLW	'M'			; M
	CALL 	ENVIAR	
	MOVLW	'G'			; G
	CALL 	ENVIAR	
	MOVLW	'F'			; F
	CALL 	ENVIAR
	MOVLW	'='			; =
	CALL	ENVIAR
	MOVLW	'1'			; 1 (MODO TEXTO)
	CALL	ENVIAR
	MOVLW	0X0D		; ENTER (COMANDO PARA CONFIGURAR MODO TEXTO AT+CMGF=1<CR>)
	CALL	ENVIAR		; QUALQUER DUVIDA, CONSULTAR "G24 AT COMMANDS REFERENCE"

	MOVLW	.250		; DELAY PARA ESTABILIZAÇÃO
	CALL	DELAY_MS
	MOVLW	.20		; DELAY PARA ESTABILIZAÇÃO
	CALL	DELAY_MS

	MOVLW	'A'			; A
	CALL 	ENVIAR
	MOVLW	'T'			; T
	CALL 	ENVIAR
	MOVLW	'+'			; +
	CALL	ENVIAR
	MOVLW	'M'			; M
	CALL 	ENVIAR
	MOVLW	'I'			; I
	CALL 	ENVIAR
	MOVLW	'P'			; P
	CALL 	ENVIAR
	MOVLW	'O'			; O
	CALL	ENVIAR
	MOVLW	'N'			; N
	CALL	ENVIAR
	MOVLW	0X0D		; (ENTER) AT+MIPON É UM COMANDO QUE INICIALIZA
						; O MÓDULO INTERNO G24. NECESSITA DE 
	CALL	ENVIAR	 	; 2 A 8s P/ SER EXECUTADO, COLOCAMOS 10S DE ESPERA

; INÍCIO DA ROTINA DE ESPERA DE 10 SEGUNDOS

	MOVLW	.10
	MOVWF	COUNTER

CONTAGEM				; A ROTINA CONTAGEM EXECUTA A MESMA FUNÇÃO DA ROTINA "PRECONTAGEM"	
	MOVLW	.250		; DELAY PARA ESTABILIZAÇÃO
	CALL	DELAY_MS
	MOVLW	.20		; DELAY PARA ESTABILIZAÇÃO
	CALL	DELAY_MS
	INCF	COUNTER
	MOVFW	COUNTER
	MOVWF	AUXCOUNTER	; AUXCOUNTER É APENAS UMA VARÁVEL AUXILIAR (PARA QUE NÃO SEJA PERDIDO O VALOR DE COUNTER)
	MOVLW	.40			; POIS O VALOR DA INSTRUÇÃO 'XORWF' LANÇA O VALOR NO REGISTRADOR F
	
	XORWF	AUXCOUNTER	; COMPARA AUXCOUNTER COM 40, SE IGUAL PROCEGUE, SE DIFERENTE VOLTA AO INICIO
	BTFSS	STATUS,Z
	GOTO	CONTAGEM
	BCF		PORTD,0


; PARA INFORMAR AO USUÁRIO QUE O MODEM INCIALIZOU
	MOVLW	'A'			; A
	CALL 	ENVIAR
	MOVLW	'T'			; T
	CALL 	ENVIAR
	MOVLW	'+'			; +
	CALL 	ENVIAR
	
	MOVLW	.10
	CALL	DELAY_MS

	MOVLW	'C'			; C
	CALL	ENVIAR
	MOVLW	'M'			; M
	CALL 	ENVIAR
	MOVLW	'G'			; G
	CALL 	ENVIAR
	MOVLW	'S'			; S
	CALL	ENVIAR
	MOVLW	'='			; =
	CALL 	ENVIAR	
	
	MOVLW	'"'			; ASPAS ABERTURA
	CALL	ENVIAR
	MOVLW	'+'			; BRASIL +55
	CALL	ENVIAR
	MOVLW	'5'			; BRASIL +55
	CALL	ENVIAR
	MOVLW	'5'			; OBRIGATORIO
	CALL	ENVIAR
	MOVLW	'8'			; RN 84
	CALL	ENVIAR
	MOVLW	'4'			; OBRIGATORIO
	CALL	ENVIAR
	MOVLW	'8'			; 1o DIGITO
	CALL	ENVIAR
	MOVLW	'8'			; 2o DIGITO
	CALL	ENVIAR
	MOVLW	'6'			; 3o DIGITO
	CALL	ENVIAR
	MOVLW	'1'			; 4o DIGITO
	CALL	ENVIAR
	MOVLW	'0'			; 5o DIGITO
	CALL	ENVIAR
	MOVLW	'0'			; 6o DIGITO
	CALL	ENVIAR
	MOVLW	'3'			; 7o DIGITO
	CALL	ENVIAR
	MOVLW	'7'         ; 8o DIGITO "+55 84 88610037 - CEL DE BIA"
	CALL 	ENVIAR
	MOVLW	'"'			; ASPAS FECHAMENTO
	CALL	ENVIAR
	
	
	MOVLW	.10
	CALL	DELAY_MS

	MOVLW	0X0D		; ENTER <CR> CARRIAGE RETURN, EXIGIDO PELO COMANDO AT
	CALL 	ENVIAR

	MOVLW	.10
	CALL	DELAY_MS
	
	
	MOVLW	'C'			; INICIO DO CORPO DE MSG
	CALL 	ENVIAR
	MOVLW	'O'
	CALL 	ENVIAR		; ESCREVE: COM OK!
	MOVLW	'M'
	CALL 	ENVIAR	
	MOVLW	' '
	CALL 	ENVIAR	
	MOVLW	'O'
	CALL 	ENVIAR	
	MOVLW	'K'
	CALL 	ENVIAR	
	MOVLW	'!'
	CALL 	ENVIAR	

	MOVLW	0X1A		; <CTRL+Z> ("SUBSTITUTE" TABELA ASCII)
	CALL	ENVIAR		; DIZ AO MODEM QUE ENCERROU O MODO DE ESCRITA DE SMS.

	MOVLW	.250
	CALL 	DELAY_MS	
	MOVLW	.250
	CALL 	DELAY_MS	; DELAY DE 500 ms PARA ESTABILIZAÇÃO


; * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
; *                  LOOP PRINCIPAL - ROTINA PRINCIPAL                      *
; * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
;  A ROTINA PRINCIPAL FICA AGUARDANDO O FINAL DA CONVERSÃO A/D E VERIFICANDO
;  SE ALGUM DADO FOI RECEBIDO PELA USART

LOOP
	BCF		PORTD,3			; LED PARA INDICAR QUE SAIU DA ROTINA DE ESCREVER NO MODEM.	
	BSF		PORTD,2			; LED PARA INDICAR QUE ESTÁ AGUARDANDO ACIONAMENTO DO BOTÃO DE PÂNICO
	BTFSC	PORTA,0			; TESTA SE O BOTÃO DE PÂNICO FOI ACIONADO
	GOTO	$-1				; NÃO, CONTINUA TESTANDO
							; SIM, ALERTA DE PERIGO. PREPARAR ENVIO DE SMS.

; * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
; *    			 ROTINA DE TRANSMISSÃO DE DADOS PARA O MODEM			    *
; * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
;  ESTA ROTINA É EXECUTADA APÓS O RECEBIMENTO DE UM DADO PELA USART.
;  ESTE DADO É, ENTÃO, TRANSMITIDO E MOSTRADO EM UM DISPLAY DE 7 SEGMENTOS.

ESCREVER_MODEM
	BCF 	RS				; CONFIGURA O DISPLAY LCD NO MODO COMANDO
	MOVLW	B'00000001'		; ENVIA COMANDO PARA LIMPAR (CLEAR) O DISPLAY
	BSF		RS				; CONFIGURA O DISPLAY LCD NO MODO COMANDO
	BCF		PORTD,2			; LED PARA INDICAR QUE NÃO ESTÁ AGUARDANDO ACIONAMENTO DO BOTÃO DE PÂNICO (BOTÃO DE PÂNICO ACIONADO)
	BSF		PORTD,3			; LED PARA INDICAR QUE ENTROU NA ROTINA DE ESCREVER NO MODEM.
	BANK1					; MUDANDO PARA BANK1 DEVIDO AO REGISTRO TXSTA SER DO BANK1
	MOVLW	B'00100110'		; MUDANDO PARA HIGH SPEED BAUD RATE
	MOVWF	TXSTA			; ACERTANDO O BAUD RATE EM 9600 BAUDS
	MOVLW	.26				; PARA QUE POSSA SER CORRETA A RECEPÇÃO
	MOVWF	SPBRG
	BANK0					; VOLTANDO AO BANK0
	MOVLW	'A'				; ESCREVE LITERAL 'A' PARA ENVIAR AO MODEM
	CALL	ENVIAR
	MOVLW	'T'				; ESCREVE LITERAL 'T' PARA ENVIAR AO MODEM
	CALL	ENVIAR
	MOVLW	'+'				; ESCREVE LITERAL '+' PARA ENVIAR AO MODEM
	CALL	ENVIAR
	MOVLW	'C'				; ESCREVE LITERAL 'C' PARA ENVIAR AO MODEM
	CALL	ENVIAR
	MOVLW	'M'				; ESCREVE LITERAL 'M' PARA ENVIAR AO MODEM
	CALL	ENVIAR
	MOVLW	'G'				; ESCREVE LITERAL 'G' PARA ENVIAR AO MODEM
	CALL	ENVIAR
	MOVLW	'S'				; ESCREVE LITERAL 'S' PARA ENVIAR AO MODEM
	CALL	ENVIAR
	MOVLW	'='				; ESCREVE LITERAL '=' PARA ENVIAR AO MODEM
	CALL	ENVIAR
	MOVLW	'"'				; ESCREVE LITERAL '"' PARA ENVIAR AO MODEM
	CALL	ENVIAR
	MOVLW	'+'				; ESCREVE DECIMAL '0' PARA ENVIAR AO MODEM
	CALL	ENVIAR
	MOVLW	'5'				; ESCREVE DECIMAL '5' PARA ENVIAR AO MODEM
	CALL	ENVIAR
	MOVLW	'5'				; ESCREVE DECIMAL '5' PARA ENVIAR AO MODEM
	CALL	ENVIAR
	MOVLW	'8'				; ESCREVE DECIMAL '8' PARA ENVIAR AO MODEM
	CALL	ENVIAR
	MOVLW	'4'				; ESCREVE DECIMAL '4' PARA ENVIAR AO MODEM
	CALL	ENVIAR
	MOVLW	'8'				; ESCREVE LITERAL '9' PARA ENVIAR AO MODEM - 1º Nº DO TELEFONE CELULAR
	CALL	ENVIAR
	MOVLW	'8'				; ESCREVE LITERAL '1' PARA ENVIAR AO MODEM - 2º Nº DO TELEFONE CELULAR
	CALL	ENVIAR
	MOVLW	'6'				; ESCREVE LITERAL '0' PARA ENVIAR AO MODEM - 3º Nº DO TELEFONE CELULAR
	CALL	ENVIAR
	MOVLW	'1'				; ESCREVE LITERAL '1' PARA ENVIAR AO MODEM - 4º Nº DO TELEFONE CELULAR
	CALL	ENVIAR
	MOVLW	'0'				; ESCREVE LITERAL '8' PARA ENVIAR AO MODEM - 5º Nº DO TELEFONE CELULAR
	CALL	ENVIAR
	MOVLW	'0'				; ESCREVE LITERAL '2' PARA ENVIAR AO MODEM - 6º Nº DO TELEFONE CELULAR
	CALL	ENVIAR
	MOVLW	'3'				; ESCREVE LITERAL '5' PARA ENVIAR AO MODEM - 7º Nº DO TELEFONE CELULAR
	CALL	ENVIAR
	MOVLW	'7'				; ESCREVE LITERAL '4' PARA ENVIAR AO MODEM - 8º Nº DO TELEFONE CELULAR
	CALL	ENVIAR
	MOVLW	'"'				; ESCREVE LITERAL '"' PARA ENVIAR AO MODEM "+55 84 88610037 - CEL DE BIA"
	CALL	ENVIAR
	MOVLW	.10
	CALL 	DELAY_MS
	MOVLW	.13				; ENVIA UM ENTER PARA O MODEM (COMANDO AT+CMGF=1)
	CALL	ENVIAR
	MOVLW	.10
	CALL 	DELAY_MS
	MOVLW	'P'				; ESCREVE LITERAL 'P' PARA ENVIAR AO MODEM
	CALL	ENVIAR
	MOVLW	'E'				; ESCREVE LITERAL 'E' PARA ENVIAR AO MODEM 
	CALL	ENVIAR
	MOVLW	'R'				; ESCREVE LITERAL 'R' PARA ENVIAR AO MODEM
	CALL	ENVIAR
	MOVLW	'I'				; ESCREVE LITERAL 'I' PARA ENVIAR AO MODEM
	CALL 	ENVIAR
	MOVLW	'G'				; ESCREVE LITERAL 'G' PARA ENVIAR AO MODEM
	CALL 	ENVIAR
	MOVLW	'O'				; ESCREVE LITERAL 'O' PARA ENVIAR AO MODEM
	CALL	ENVIAR
	MOVLW	'!'				; ESCREVE LITERAL '!' PARA ENVIAR AO MODEM 
	CALL	ENVIAR			; MENSAGEM "PERIGO!" ENVIADA
	MOVLW	.26				; LITERAL SUB (EQUIVALENTE AO COMANDO CTRL+Z)
	CALL	ENVIAR			; ESCREVE NO MODEM O QUE FOI PREPARADO NA ROTINA PASSADA
	MOVLW	.250
	CALL 	DELAY_MS	
	MOVLW	.250
	CALL 	DELAY_MS
	GOTO	LOOP

ENVIAR

	BANK1				; PASSA PARA O BANK1 POIS O REGISTRADOR TXSTA ESTA NO BANK1
	BTFSS	TXSTA,TRMT	; BUFFER VAZIO?
	GOTO	$-1			; NÃO. ESPERA ATÉ FICAR VAZIO (ATÉ A TRANSMISSÃO PASSADA ACABAR)
	BANK0				; SIM. ENTÃO TRANSMITE O NOVO VALOR.  
	MOVWF	TXREG		; MOVE O VALOR A SER TRANSMITIDO PARA O TXREG
	RETURN				; UMA NOVA ORDEM DE ENVIO.



	
; * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
; *                              FIM DO PROGRAMA                            *
; * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *

	END				; FIM DO PROGRAMA

; ************************************************************************************
; *		ÁREA RESERVADA PARA ESCREVER OBSERVAÇÕES E ALTERAÇÕES A SEREM FEITAS *
; ************************************************************************************

; 16/07/2010 - TESTES FINAIS POR FAZER. AS ROTINAS SE MOSTRARAM EFICAZES SEPARADAMENTE, RESTA
;		  SER FEITA A JUNÇÃO DAS PARTES (MEDIDOR+INTERFACE DE COMUNICAÇÃO+MODEM) E OS TESTES
;		  FINAIS.