"""
# News Article Summarization App

Welcome to the **News Article Summarization App**! This application allows you to generate concise summaries of long news articles using two advanced Natural Language Processing (NLP) techniques:

1. **Extractive Summarization**: Uses the TextRank algorithm to extract the most important sentences from the article.
2. **Abstractive Summarization**: Uses the BART model from Hugging Face Transformers to generate a summary in its own words.

## How to Use
1. Paste your news article into the text box below.
2. Click the "Summarize" button.
3. View the extractive and abstractive summaries generated by the model.

## Technologies Used
- **Python**: Core programming language.
- **Streamlit**: For building and deploying the web app.
- **Transformers (Hugging Face)**: For abstractive summarization using BART.
- **Sumy**: For extractive summarization using TextRank.
"""

import streamlit as st
from text_summarization import extractive_summary, abstractive_summary

st.title("News Article Summarization")
st.write("Upload or paste a news article to generate a summary.")

# Input text
input_text = st.text_area("Paste your news article here:", height=200)

# Summarization options
if st.button("Summarize"):
    if input_text:
        st.subheader("Extractive Summary")
        st.write(extractive_summary(input_text))
        
        st.subheader("Abstractive Summary")
        st.write(abstractive_summary(input_text))
    else:
        st.error("Please enter some text to summarize.")