"""
# News Article Summarization App

Welcome to the **News Article Summarization App**! This application allows you to generate concise summaries of long news articles using two advanced Natural Language Processing (NLP) techniques:

1. **Extractive Summarization**: Uses the TextRank algorithm to extract the most important sentences from the article.
2. **Abstractive Summarization**: Uses the BART model from Hugging Face Transformers to generate a summary in its own words.

## How to Use
1. Paste your news article into the text box below.
2. Click the "Summarize" button.
3. View the extractive and abstractive summaries generated by the model.

## Technologies Used
- **Python**: Core programming language.
- **Streamlit**: For building and deploying the web app.
- **Transformers (Hugging Face)**: For abstractive summarization using BART.
- **Sumy**: For extractive summarization using TextRank.
"""

import nltk
from sumy.parsers.plaintext import PlaintextParser
from sumy.nlp.tokenizers import Tokenizer
from sumy.summarizers.text_rank import TextRankSummarizer
from transformers import pipeline

# Extractive Summarization using TextRank
def extractive_summary(text, sentences_count=3):
    parser = PlaintextParser.from_string(text, Tokenizer("english"))
    summarizer = TextRankSummarizer()
    summary = summarizer(parser.document, sentences_count)
    return " ".join([str(sentence) for sentence in summary])

# Abstractive Summarization using Hugging Face Transformers (T5/BART)
def abstractive_summary(text, max_length=130):
    summarizer = pipeline("summarization", model="facebook/bart-large-cnn")
    summary = summarizer(text, max_length=max_length, min_length=30, do_sample=False)
    return summary[0]['summary_text']

# Example Usage
if __name__ == "__main__":
    text = """
    Artificial intelligence (AI) is intelligence demonstrated by machines, in contrast to the natural intelligence displayed by humans and animals. 
    Leading AI textbooks define the field as the study of "intelligent agents": any device that perceives its environment and takes actions that maximize its chance of successfully achieving its goals. 
    Colloquially, the term "artificial intelligence" is often used to describe machines (or computers) that mimic cognitive functions that humans associate with the human mind, such as learning and problem-solving.
    """
    print("Extractive Summary:")
    print(extractive_summary(text))
    print("\nAbstractive Summary:")
    print(abstractive_summary(text))